### ISSUE TITLE
Live demo needs update

### ISSUE THREAD

**Issue by ryderwishart** [jcuenod/vue-tree-dnd#1]
I can create new folders, but can't drag/drop

**Comment by jcuenod** [comment]
Interesting. Are you getting errors in the console?

**Comment by ryderwishart** [comment]
I looked there, but nothing!

**Comment by jcuenod** [comment]
Thanks, I'm also having issues on Chrome here. Hadn't tested!

**Comment by ryderwishart** [comment]
Initially I was actually using Safari as well. I'm guessing you used Firefox for dev?

**Comment by jcuenod** [comment]
Oh interesting, so safari is not working either? Yes, I use FF for everything :)

**Comment by jcuenod** [comment]
@ryderwishart would you mind taking another look?
